authapp/urls.py
from django.urls import path

from authapp import views
from authapp.apps import AuthappConfig

app_name = AuthappConfig.name

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path(
        "profile_edit/<int:pk>/",
        views.ProfileEditView.as_view(),
        name="profile_edit",
    ),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", RedirectView.as_view(url="mainapp/")),
    path("social_auth/", include("social_django.urls", namespace="social")),
    path("mainapp/", include("mainapp.urls", namespace="mainapp")),
    path("authapp/", include("authapp.urls", namespace="authapp")),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from pathlib import Path
from time import time

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.core.mail import send_mail
from django.db import models
from django.utils.translation import gettext_lazy as _


def users_avatars_path(instance, filename):
    # file will be uploaded to
    #   MEDIA_ROOT / user_<username> / avatars / <filename>
    num = int(time() * 1000)
    suff = Path(filename).suffix
    return "user_{0}/avatars/{1}".format(instance.username, f"pic_{num}{suff}")


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username_validator = ASCIIUsernameValidator()

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. ASCII letters and digits only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    last_name = models.CharField(_("last name"), max_length=150, blank=True)
    age = models.PositiveIntegerField(blank=True, null=True)
    avatar = models.ImageField(upload_to=users_avatars_path, blank=True, null=True)
    email = models.CharField(
        _("email address"),
        max_length=256,
        unique=True,
        error_messages={
            "unique": _("A user with that email address already exists."),
        },
    )
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. \
            Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), auto_now_add=True)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["email"]

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

authapp/forms.py
import os

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class CustomUserCreationForm(UserCreationForm):
    field_order = [
        "username",
        "password1",
        "password2",
        "email",
        "first_name",
        "last_name",
        "age",
        "avatar",
    ]

    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "age",
            "avatar",
        )
        field_classes = {"username": UsernameField}


class CustomUserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "age",
            "avatar",
        )
        field_classes = {"username": UsernameField}

    def clean_avatar(self):
        arg_as_str = "avatar"
        if arg_as_str in self.changed_data and self.instance.avatar:
            if os.path.exists(self.instance.avatar.path):
                os.remove(self.instance.avatar.path)
        return self.cleaned_data.get(arg_as_str)

    def clean_age(self):
        data = self.cleaned_data.get("age")
        if data:
            if data < 10 or data > 100:
                raise ValidationError(_("Please, enter a valid age!"))
        return data

authapp/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, UpdateView

from authapp import forms


class CustomLoginView(LoginView):
    def form_valid(self, form):
        ret = super().form_valid(form)
        message = _("Login success!<br>Hi, %(username)s") % {
            "username": self.request.user.get_full_name()
            if self.request.user.get_full_name()
            else self.request.user.get_username()
        }
        messages.add_message(self.request, messages.INFO, mark_safe(message))
        return ret

    def form_invalid(self, form):
        for _unused, msg in form.error_messages.items():
            messages.add_message(
                self.request,
                messages.WARNING,
                mark_safe(f"Something goes worng:<br>{msg}"),
            )
        return self.render_to_response(self.get_context_data(form=form))


class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.add_message(self.request, messages.INFO, _("See you later!"))
        return super().dispatch(request, *args, **kwargs)


class RegisterView(CreateView):
    model = get_user_model()
    form_class = forms.CustomUserCreationForm
    success_url = reverse_lazy("mainapp:main_page")


class ProfileEditView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = forms.CustomUserChangeForm

    def test_func(self):
        return True if self.request.user.pk == self.kwargs.get("pk") else False

    def get_success_url(self):
        return reverse_lazy("authapp:profile_edit", args=[self.request.user.pk])

authapp/templates/customuser_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row justify-content-center my-2">
  <div class="col-lg-6">

    {% if user.is_anonymous %}
    <h3>Регистрация нового пользователя</h3>
    {% else %}
    <h3>Редактировать профиль</h3>
    <div class="row justify-content-center">
      <div class="col-sm-7 col-md-5 col-lg-4">
        {% if user.avatar %}
        <img src="{{ user.avatar.url }}" alt="" width="100%">
        {% else %}
        <img src="{{ MEDIA_URL }}avatar_default.svg" alt="" width="100%">
        {% endif %}
      </div>
    </div>
    {% endif %}

    <form method="post" class="mt-2" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary btn-block">
        {% if user.is_anonymous %}
        Зарегистрироваться
        {% else %}
        Сохранить
        {% endif %}
      </button>
    </form>
  </div>
</div>
{% endblock content %}

authapp/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center my-2">
  <div class="col-lg-6">
    <h3>Регистрация нового пользователя</h3>
    <form method="post" class="mt-2" enctype="multipart/form-data">
      {% csrf_token %}
      <div id="div_id_username" class="form-group"> <label for="id_username"
          class=" requiredField">
          Username<span class="asteriskField">*</span> </label>
        <div class=""> <input type="text" name="username" maxlength="150"
            class="textinput textInput form-control" required=""
            id="id_username"> <small id="hint_id_username"
            class="form-text text-muted">Required. 150 characters or fewer.
            Letters, digits and @/./+/-/_ only.</small> </div>
      </div>
      <div id="div_id_password1" class="form-group"> <label for="id_password1"
          class=" requiredField">
          Password<span class="asteriskField">*</span> </label>
        <div class=""> <input type="password" name="password1"
            autocomplete="new-password" class="textinput textInput form-control"
            required="" id="id_password1"> <small id="hint_id_password1"
            class="form-text text-muted">
            <ul>
              <li>Your password can’t be too similar to your other personal
                information.</li>
              <li>Your password must contain at least 8 characters.</li>
              <li>Your password can’t be a commonly used password.</li>
              <li>Your password can’t be entirely numeric.</li>
            </ul>
          </small> </div>
      </div>
      <div id="div_id_password2" class="form-group"> <label for="id_password2"
          class=" requiredField">
          Password confirmation<span class="asteriskField">*</span> </label>
        <div class=""> <input type="password" name="password2"
            autocomplete="new-password" class="textinput textInput form-control"
            required="" id="id_password2"> <small id="hint_id_password2"
            class="form-text text-muted">Enter the same password as before, for
            verification.</small> </div>
      </div>
      <div id="div_id_first_name" class="form-group"> <label for="id_first_name"
          class="">
          First name
        </label>
        <div class=""> <input type="text" name="first_name" maxlength="150"
            class="textinput textInput form-control" id="id_first_name"> </div>
      </div>
      <div id="div_id_last_name" class="form-group"> <label for="id_last_name"
          class="">
          Last name
        </label>
        <div class=""> <input type="text" name="last_name" maxlength="150"
            class="textinput textInput form-control" id="id_last_name"> </div>
      </div>
      <div id="div_id_age" class="form-group"> <label for="id_age" class="">
          Age
        </label>
        <div class=""> <input type="number" name="age" min="0"
            class="numberinput form-control" id="id_age"> </div>
      </div>
      <div id="div_id_avatar" class="form-group"> <label for="id_avatar"
          class="">
          Avatar
        </label>
        <div class=""> <input type="file" name="avatar" accept="image/*"
            class="clearablefileinput form-control-file" id="id_avatar"> </div>
      </div>
      <div id="div_id_email" class="form-group"> <label for="id_email"
          class=" requiredField">
          Email address<span class="asteriskField">*</span> </label>
        <div class=""> <input type="text" name="email" maxlength="256"
            class="textinput textInput form-control" required="" id="id_email">
        </div>
      </div>

      <button type="submit"
        class="btn btn-primary btn-block">Зарегистрироваться</button>
    </form>
  </div>
</div>

{% endblock content %}